core/blog/api/v1/urls.py
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register('task', views.TaskModelViewSet, basename='task')
urlpatterns = router.urls

core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.BaseView.as_view(), name='base-view'),
    path('task/', views.TaskListView.as_view(), name="task-list"),
    path('task/<int:pk>/', views.TaskDetailView.as_view(), name="task-detail"),
    path('task/create/', views.TaskCreateView.as_view(), name="task-create"),
    path('task/<int:pk>/edit/', views.TaskEditView.as_view(), name="task-edit"),
    path('task/<int:pk>/delete/', views.TaskDeleteView.as_view(), name="task-delete"),
    path('api/v1/', include('blog.api.v1.urls')),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('blog.urls')),
    path('swagger.<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]


# Serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Task(models.Model):
    '''
    this is a class to define tasks for todo app
    '''
    author = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def get_snippet(self):
        return self.description[0:5]
    
    def get_absolute_api_url(self):
        return reverse('blog:api-v1:task-detail', kwargs={'pk': self.pk})
    

core/blog/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields = ['title', 'description', 'completed']

core/blog/api/v1/views.py
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .serializers import TaskSerializer
from ...models import Task
from rest_framework import viewsets
from .permissions import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import DefaultPagination
from .filters import TaskFilter

class TaskModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly] 
    serializer_class = TaskSerializer 
    queryset = Task.objects.filter(completed=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    search_fields = ['title', 'description']
    ordering_fields = ['updated_at']
    pagination_class = DefaultPagination 
    filterset_class = TaskFilter
    
   
   
    

core/blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Task
from .forms import TaskForm
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import Profile


class BaseView(TemplateView):
    template_name = 'base.html'
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            request.session['user_id'] = request.user.id
            try:
                profile = Profile.objects.get(user=request.user)
                request.session['first_name'] = profile.first_name
            except Profile.DoesNotExist:
                request.session['first_name'] = ''  # Handle missing profile gracefully
        
        return super().dispatch(request, *args, **kwargs)
    

class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    paginate_by = 2

    def get_queryset(self):
        # Filter queryset to show only tasks for the logged-in user
        return Task.objects.filter(author__user__email=self.request.user).order_by('-id')

        
    


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    
    
class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    # fields = ['author', 'title', 'description', 'completed']
    form_class = TaskForm
    success_url = '/task/'
    
    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        form.instance.author = profile 
        return super().form_valid(form)
        
    
class TaskEditView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    success_url = '/task/'
    
    
class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = '/task/'
    
    
    

core/templates/blog/task_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}
{% block content %}
<div class="confirm-box">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a href="{% url 'blog:task-list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

core/templates/blog/task_detail.html
{% extends 'base.html' %}

{% block title %}Task Detail{% endblock %}
{% block content %}
    <div class="task-container">
        <h2>{{ object.title }}</h2>
        <ul class="task-details">
            <li><strong>Author:</strong> {{ object.author }}</li>
            <li><strong>Created At:</strong> {{ object.created_at|date:"Y-m-d H:i" }}</li>
            <li><strong>Description:</strong> {{ object.description }}</li>
            <li><strong>Status:</strong> {% if object.completed %} ✅ Completed {% else %} ⏳ Pending {% endif %}</li>
        </ul>
    </div>
{% endblock %}

core/templates/blog/task_form.html
{% extends 'base.html' %}

{% block title %}Task Form{% endblock %}

{% block content %}
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save">
        </form>
    </div>
{% endblock %}

core/templates/blog/task_list.html
{% extends 'base.html' %}

{% block title %}Task List{% endblock %}

{% block content %}
    <div class="task-container">
        {% for task in tasks %}
            <div class="task-card">
                <h3><a href="{% url 'blog:task-detail' pk=task.id %}">{{ task.title }}</a></h3>
                <p><strong>Author:</strong> {{ task.author.first_name }} {{ task.author.last_name }}</p>
                <p>{{ task.description }}</p>
                <li><strong>Status:</strong> {% if task.completed %} ✅ Completed {% else %} ⏳ Pending {% endif %}</li>
                <div class="actions">
                    <a href="{% url 'blog:task-edit' pk=task.id %}" class="btn edit">Edit</a>
                    <a href="{% url 'blog:task-delete' pk=task.id %}" class="btn delete">Delete</a><hr>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if page_obj.has_previous %}
            <a href="?page=1" class="btn">&laquo; First</a>
            <a href="?page={{ page_obj.previous_page_number }}" class="btn">Previous</a>
        {% endif %}

        <span class="current-page">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" class="btn">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" class="btn">Last &raquo;</a>
        {% endif %}
    </div>
{% endblock %}